package com.pschsch.kformatter.core.countries.internal

import com.pschsch.kformatter.core.optin.IncubatingMaskaradeAPI

@OptIn(IncubatingMaskaradeAPI::class)
internal fun createCountriesList(
    excludeCodes : List<String> = emptyList()
): List<CountryImpl> {
    var id = 0
    fun createCountry(
        isoCode: String,
        countryCode: String,
        englishName: String,
        mask: String,
        separator: Char = if (countryCode.startsWith("+1")) '-' else ' ',
    ): CountryImpl? {
        id += 1
        if (excludeCodes.contains(isoCode)) return null
        return CountryImpl(id, isoCode, countryCode, separator, mask, englishName)
    }

    val countries: MutableList<CountryImpl?> = ArrayList()
    countries.add(createCountry("ad", "+376", "Andorra", "DDD DDD"))
    countries.add(createCountry("ae", "+971", "United Arab Emirates (UAE)", "DD DDD DDDD"))
    countries.add(createCountry("af", "+93", "Afghanistan", "DD DDD DDDD"))
    countries.add(createCountry("ag", "+1-268", "Antigua and Barbuda", "DDD-DDDD"))
    countries.add(createCountry("ai", "+1-264", "Anguilla", "DDD-DDDD"))
    countries.add(createCountry("al", "+355", "Albania", "DD DDD DDDD"))
    countries.add(createCountry("am", "+374", "Armenia", "DD DDDDDD"))
    countries.add(createCountry("ao", "+244", "Angola", "DDD DDD DDD"))
    countries.add(createCountry("aq", "+672", "Antarctica", "DDD DDD"))
    countries.add(createCountry("ar", "+54", "Argentina", "D DD DDDD-DDDD"))
    countries.add(createCountry("as", "+1-684", "American Samoa", "DDD-DDDD"))
    countries.add(createCountry("at", "+43", "Austria", "DDD DDDDDD"))
    countries.add(createCountry("au", "+61", "Australia", "DDD DDD DDD"))
    countries.add(createCountry("aw", "+297", "Aruba", "DDD DDDD"))
    countries.add(createCountry("ax", "+358", "Åland Islands", "DD DDDDDDD"))
    countries.add(createCountry("az", "+994", "Azerbaijan", "(DD) DDD-DD-DD"))
    countries.add(createCountry("ba", "+387", "Bosnia And Herzegovina", "DD DDD DDD"))
    countries.add(createCountry("bb", "+1-246", "Barbados", "DDD-DDDD"))
    countries.add(createCountry("bd", "+880", "Bangladesh", "DDDD-DDDDDD"))
    countries.add(createCountry("be", "+32", "Belgium", "DDD DD DD DD"))
    countries.add(createCountry("bf", "+226", "Burkina Faso", "DD DD DD DD"))
    countries.add(createCountry("bg", "+359", "Bulgaria", "DD DDD DDD"))
    countries.add(createCountry("bh", "+973", "Bahrain", "DDDD DDDD"))
    countries.add(createCountry("bi", "+257", "Burundi", "DD DD DD DD"))
    countries.add(createCountry("bj", "+229", "Benin", "DD DD DD DD"))
    countries.add(createCountry("bl", "+590", "Saint Barthélemy", "DDD DD DD DD"))
    countries.add(createCountry("bm", "+1", "Bermuda", "DDD-DDD-DDDD"))
    countries.add(createCountry("bn", "+673", "Brunei Darussalam", "DDD DDDD"))
    countries.add(createCountry("bo", "+591", "Bolivia, Plurinational State Of", "DDDD DDDD"))
    countries.add(createCountry("br", "+55", "Brazil", "DD DDDDD-DDDD"))
    countries.add(createCountry("bs", "+1-242", "Bahamas", "DDD-DDDD"))
    countries.add(createCountry("bt", "+975", "Bhutan", "DD DD DD DD"))
    countries.add(createCountry("bw", "+267", "Botswana", "DD DDD DDD"))
    countries.add(createCountry("by", "+375", "Belarus", "(DD) DDD-DD-DD"))
    countries.add(createCountry("bz", "+501", "Belize", "DDD-DDDD"))
    countries.add(createCountry("ca", "+1", "Canada", "DDD-DDD-DDDD"))
    countries.add(createCountry("cc", "+61", "Cocos (keeling) Islands", "DDD DDD DDD"))
    countries.add(createCountry("cd", "+243", "Congo, The Democratic Republic Of The", "DDD DDD DDD"))
    countries.add(createCountry("cf", "+236", "Central African Republic", "DD DD DD DD"))
    countries.add(createCountry("cg", "+242", "Congo", "DDDD DDDD"))
    countries.add(createCountry("ch", "+41", "Switzerland", "DD DDD DD DD"))
    countries.add(createCountry("ci", "+225", "Côte D'ivoire", "DD DD DD DD"))
    countries.add(createCountry("ck", "+682", "Cook Islands", "DD DDD"))
    countries.add(createCountry("cl", "+56", "Chile", "D DDDD DDDD"))
    countries.add(createCountry("cm", "+237", "Cameroon", "D DD DD DD DD"))
    countries.add(createCountry("cn", "+86", "China", "DDD DDDD DDDD"))
    countries.add(createCountry("co", "+57", "Colombia", "DDD DDDDDDD"))
    countries.add(createCountry("cr", "+506", "Costa Rica", "DDDD DDDD"))
    countries.add(createCountry("cu", "+53", "Cuba", "D DDDDDDD"))
    countries.add(createCountry("cv", "+238", "Cape Verde", "DDD DD DD"))
    countries.add(createCountry("cw", "+599", "Curaçao", "D DDD DDDD"))
    countries.add(createCountry("cx", "+61", "Christmas Island", "DDD DDD DDD"))
    countries.add(createCountry("cy", "+357", "Cyprus", "DD DDDDDD"))
    countries.add(createCountry("cz", "+420", "Czech Republic", "DDD DDD DDD"))
    countries.add(createCountry("de", "+49", "Germany", "DDDD DDDDDD"))
    countries.add(createCountry("dj", "+253", "Djibouti", "DD DD DD DD"))
    countries.add(createCountry("dk", "+45", "Denmark", "DD DD DD DD"))
    countries.add(createCountry("dm", "+1-767", "Dominica", "DDD-DDDD"))
    countries.add(createCountry("do", "+1", "Dominican Republic", "DDD-DDD-DDDD"))
    countries.add(createCountry("dz", "+213", "Algeria", "DDD DD DD DD"))
    countries.add(createCountry("ec", "+593", "Ecuador", "DD DDD DDDD"))
    countries.add(createCountry("ee", "+372", "Estonia", "DDDD DDDD"))
    countries.add(createCountry("eg", "+20", "Egypt", "DDD DDD DDDD"))
    countries.add(createCountry("er", "+291", "Eritrea", "D DDD DDD"))
    countries.add(createCountry("es", "+34", "Spain", "DDD DD DD DD"))
    countries.add(createCountry("et", "+251", "Ethiopia", "DD DDD DDDD"))
    countries.add(createCountry("fi", "+358", "Finland", "DDD DDDDDD"))
    countries.add(createCountry("fj", "+679", "Fiji", "DDD DDDD"))
    countries.add(createCountry("fk", "+500", "Falkland Islands (malvinas)", "DDDDD"))
    countries.add(createCountry("fm", "+691", "Micronesia, Federated States Of", "DDD DDDD"))
    countries.add(createCountry("fo", "+298", "Faroe Islands", "DDDDDD"))
    countries.add(createCountry("fr", "+33", "France", "D DD DD DD DD"))
    countries.add(createCountry("ga", "+241", "Gabon", "D DD DD DD"))
    countries.add(createCountry("gb", "+44", "United Kingdom", "DDDD DDDDDD"))
    countries.add(createCountry("gd", "+1-473", "Grenada", "DDD-DDDD"))
    countries.add(createCountry("ge", "+995", "Georgia", "DDD-DDD-DDD"))
    countries.add(createCountry("gf", "+594", "French Guyana", "DDD DD DD DD"))
    countries.add(createCountry("gg", "+44", "Guernsey", "DDD DDD"))
    countries.add(createCountry("gh", "+233", "Ghana", "DD DDD DDDD"))
    countries.add(createCountry("gi", "+350", "Gibraltar", "DDDDDDDD"))
    countries.add(createCountry("gl", "+299", "Greenland", "DD DD DD"))
    countries.add(createCountry("gm", "+220", "Gambia", "DDD DDDD"))
    countries.add(createCountry("gn", "+224", "Guinea", "DDD DD DD DD"))
    countries.add(createCountry("gp", "+450", "Guadeloupe", "DDD DD DD DD"))
    countries.add(createCountry("gq", "+240", "Equatorial Guinea", "DDD DDD DDD"))
    countries.add(createCountry("gr", "+30", "Greece", "DDD DDD DDDD"))
    countries.add(createCountry("gt", "+502", "Guatemala", "DDDD DDDD"))
    countries.add(createCountry("gu", "+1-671", "Guam", "DDD-DDDD"))
    countries.add(createCountry("gw", "+245", "Guinea-bissau","DDD DDD DDD"))
    countries.add(createCountry("gy", "+592", "Guyana", "DDD DDDD"))
    countries.add(createCountry("hk", "+852", "Hong Kong", "DDDD DDDD"))
    countries.add(createCountry("hn", "+504", "Honduras", "DDDD-DDDD"))
    countries.add(createCountry("hr", "+385", "Croatia", "DD DDD DDDD"))
    countries.add(createCountry("ht", "+509", "Haiti", "DD DD DDDD"))
    countries.add(createCountry("hu", "+36", "Hungary", "DD DDD DDDD"))
    countries.add(createCountry("id", "+62", "Indonesia", "DD DDDD DDDD"))
    countries.add(createCountry("ie", "+353", "Ireland", "DDD DDD DDDD"))
    countries.add(createCountry("il", "+972", "Israel", "DD-DDD-DDDD"))
    countries.add(createCountry("im", "+44-1624", "Isle Of Man", "DDD DDD"))
    countries.add(createCountry("is", "+354", "Iceland", ""))
    countries.add(createCountry("in", "+91", "India", "DDD DDD D"))
    countries.add(createCountry("io", "+246", "British Indian Ocean Territory", ""))
    countries.add(createCountry("iq", "+964", "Iraq", "DDDD DDD DDDD"))
    countries.add(createCountry("ir", "+98", "Iran, Islamic Republic Of", "DDD DDDD DDDD"))
    countries.add(createCountry("it", "+39", "Italy", "DDD DDD DDDD"))
    countries.add(createCountry("je", "+44-1481", "Jersey",  "DDD DDD"))
    countries.add(createCountry("jm", "+1-876", "Jamaica", "DDD-DDDD"))
    countries.add(createCountry("jo", "+962", "Jordan", "D DDDD DDDD"))
    countries.add(createCountry("jp", "+81", "Japan", "-DDDD-DDDD"))
    countries.add(createCountry("ke", "+254", "Kenya", "DDD DDDDDD"))
    countries.add(createCountry("kg", "+996", "Kyrgyzstan", "(DDD) DDD-DDD"))
    countries.add(createCountry("kh", "+855", "Cambodia",  "DD DDD DDD"))
    countries.add(createCountry("ki", "+686", "Kiribati", ""))
    countries.add(createCountry("km", "+269", "Comoros", "DDD DD DD"))
    countries.add(createCountry("kn", "+1-869", "Saint Kitts and Nevis", "DDD-DDDD"))
    countries.add(createCountry("kp", "+850", "North Korea", "DDD DDD DDDD"))
    countries.add(createCountry("kr", "+82", "South Korea", "-DDDD-DDDD"))
    countries.add(createCountry("kw", "+965", "Kuwait", "DDD DDDDD"))
    countries.add(createCountry("ky", "+1-345", "Cayman Islands", "DDD-DDDD"))
    countries.add(createCountry("kz", "+7", "Kazakhstan", "(DDD) DDD-DD-DD"))
    countries.add(createCountry("la", "+856", "Lao People's Democratic Republic", "DD DD DDD DDD"))
    countries.add(createCountry("lb", "+961", "Lebanon", "DD DDD DDD"))
    countries.add(createCountry("lc", "+1-758", "Saint Lucia", "DDD-DDDD"))
    countries.add(createCountry("li", "+423", "Liechtenstein", ""))
    countries.add(createCountry("lk", "+94", "Sri Lanka", "DD DDD DDDD"))
    countries.add(createCountry("lr", "+231", "Liberia", "DD DDD DDDD"))
    countries.add(createCountry("ls", "+266", "Lesotho", "DDDD DDDD"))
    countries.add(createCountry("lt", "+370", "Lithuania", "DDD DDDDD"))
    countries.add(createCountry("lu", "+352", "Luxembourg", "DDD DDD DDD"))
    countries.add(createCountry("lv", "+371", "Latvia", "DD DDD DDD"))
    countries.add(createCountry("ly", "+218", "Libya", "DD-DDDDDDD"))
    countries.add(createCountry("ma", "+212", "Morocco", "DDD-DDDDDD"))
    countries.add(createCountry("mc", "+377", "Monaco", "D DD DD DD DD"))
    countries.add(createCountry("md", "+373", "Moldova, Republic Of", "DDD DDD-DD"))
    countries.add(createCountry("me", "+382", "Montenegro", "DD DDD DDD"))
    countries.add(createCountry("mf", "+590", "Saint Martin", "DDD DD DD DD"))
    countries.add(createCountry("mg", "+261", "Madagascar", "DD DD DDD DD"))
    countries.add(createCountry("mh", "+692", "Marshall Islands", "DDD-DDDD"))
    countries.add(createCountry("mk", "+389", "Macedonia (FYROM)", "DD DDD DDD"))
    countries.add(createCountry("ml", "+223", "Mali",  "DD DD DD DD"))
    countries.add(createCountry("mm", "+95", "Myanmar",  "D DDD DDDD"))
    countries.add(createCountry("mn", "+976", "Mongolia",  "DDDD DDDD"))
    countries.add(createCountry("mo", "+853", "Macau",  "DDDD DDDD"))
    countries.add(createCountry("mp", "+1-670", "Northern Mariana Islands", "DDD-DDDD"))
    countries.add(createCountry("mq", "+596", "Martinique",  "DDD DD DD DD"))
    countries.add(createCountry("mr", "+222", "Mauritania",  "DD DD DD DD"))
    countries.add(createCountry("ms", "+1-664", "Montserrat", "DDD-DDDD"))
    countries.add(createCountry("mt", "+356", "Malta", "DDDD DDDD"))
    countries.add(createCountry("mu", "+230", "Mauritius", "DDDD DDDD"))
    countries.add(createCountry("mv", "+960", "Maldives", "DDD-DDDD"))
    countries.add(createCountry("mw", "+265", "Malawi", "DDD DD DD DD"))
    countries.add(createCountry("mx", "+52", "Mexico", "DDD DDD DDDD"))
    countries.add(createCountry("my", "+60", "Malaysia", "DD-DDD DDDD"))
    countries.add(createCountry("mz", "+258", "Mozambique", "DD DDD DDDD"))
    countries.add(createCountry("na", "+264", "Namibia", "DD DDD DDDD"))
    countries.add(createCountry("nc", "+687", "New Caledonia", "DD.DD.DD"))
    countries.add(createCountry("ne", "+227", "Niger", "DD DD DD DD"))
    countries.add(createCountry("nf", "+672", "Norfolk Islands", "D DDDDD"))
    countries.add(createCountry("ng", "+234", "Nigeria", "DDD DDD DDDD"))
    countries.add(createCountry("ni", "+505", "Nicaragua", ""))
    countries.add(createCountry("nl", "+31", "Netherlands", "D DDDDDDDD"))
    countries.add(createCountry("no", "+47", "Norway", "DDD DD DDD"))
    countries.add(createCountry("np", "+977", "Nepal", "DDD-DDDDDDD"))
    countries.add(createCountry("nr", "+674", "Nauru", "DDD DDDD"))
    countries.add(createCountry("nu", "+683", "Niue", "DDD DDDD"))
    countries.add(createCountry("nz", "+64", "New Zealand", "DD DDD DDDD"))
    countries.add(createCountry("om", "+968", "Oman", "DDDD DDDD"))
    countries.add(createCountry("pa", "+507", "Panama", "DDDD-DDDD"))
    countries.add(createCountry("pe", "+51", "Peru", "DDD DDD DDD"))
    countries.add(createCountry("pf", "+689", "French Polynesia", "DD DD DD DD"))
    countries.add(createCountry("pg", "+675", "Papua New Guinea", "DDDD DDDD"))
    countries.add(createCountry("ph", "+63", "Philippines", "DDD DDD DDDD"))
    countries.add(createCountry("pk", "+92", "Pakistan", "DDD DDDDDDD"))
    countries.add(createCountry("pl", "+48", "Poland", "DDD DDD DDD"))
    countries.add(createCountry("pm", "+508", "Saint Pierre And Miquelon", "DD DD DD"))
    countries.add(createCountry("pn", "+870", "Pitcairn Islands", ""))
    countries.add(createCountry("pr", "+1", "Puerto Rico", "DDD-DDD-DDDD"))
    countries.add(createCountry("ps", "+970", "Palestine", "DDD DDD DDD"))
    countries.add(createCountry("pt", "+351", "Portugal", "DDD DDD DDD"))
    countries.add(createCountry("pw", "+680", "Palau", "DDD DDDD"))
    countries.add(createCountry("py", "+595", "Paraguay", "DDD DDDDDD"))
    countries.add(createCountry("qa", "+974", "Qatar", "DDDD DDDD"))
    countries.add(createCountry("re", "+262", "Réunion", "DDD DD DD DD"))
    countries.add(createCountry("ro", "+40", "Romania", "DDD DDD DDD"))
    countries.add(createCountry("rs", "+381", "Serbia", "DD DDDDDDD"))
    countries.add(createCountry("ru", "+7", "Russian Federation", "(DDD) DDD-DD-DD"))
    countries.add(createCountry("rw", "+250", "Rwanda", "DDD DDD DDD"))
    countries.add(createCountry("sa", "+966", "Saudi Arabia", "DD DDD DDDD"))
    countries.add(createCountry("sb", "+677", "Solomon Islands", "DD DDDDD"))
    countries.add(createCountry("sc", "+248", "Seychelles", "D DDD DDD"))
    countries.add(createCountry("sd", "+249", "Sudan", "DD DDD DDDD"))
    countries.add(createCountry("se", "+46", "Sweden", "DD DDD DD DD"))
    countries.add(createCountry("sg", "+65", "Singapore", "DDDD DDDD"))
    countries.add(createCountry("sh", "+290", "Saint Helena, Ascension And Tristan Da Cunha",  "DDDDD"))
    countries.add(createCountry("si", "+386", "Slovenia",  "DDD DDD DDD"))
    countries.add(createCountry("sk", "+421", "Slovakia",  "DDD DDD DDD"))
    countries.add(createCountry("sl", "+232", "Sierra Leone",  "DD DDDDDD"))
    countries.add(createCountry("sm", "+378", "San Marino",  "DD DD DD DD"))
    countries.add(createCountry("sn", "+221", "Senegal",  "DD DDD DD DD"))
    countries.add(createCountry("so", "+252", "Somalia",  "D DDDDDDD"))
    countries.add(createCountry("sr", "+597", "Suriname",  "DDD-DDDD"))
    countries.add(createCountry("ss", "+211", "South Sudan", "DDD DDD DDD"))
    countries.add(createCountry("st", "+239", "Sao Tome And Principe", "DDD DDDD"))
    countries.add(createCountry("sv", "+503", "El Salvador", "DDDD DDDD"))
    countries.add(createCountry("sx", "+1-721", "Sint Maarten", "DDD-DDDD"))
    countries.add(createCountry("sy", "+963", "Syrian Arab Republic", "DDD DDD DDD"))
    countries.add(createCountry("sz", "+268", "Swaziland", "DDDD DDDD"))
    countries.add(createCountry("tc", "+1-649", "Turks and Caicos Islands", "DDD-DDDD"))
    countries.add(createCountry("td", "+235", "Chad", "DD DD DD DD"))
    countries.add(createCountry("tg", "+228", "Togo", "DD DD DD DD"))
    countries.add(createCountry("th", "+66", "Thailand", "DD DDD DDDD"))
    countries.add(createCountry("tj", "+992", "Tajikistan", "DDD DD DDDD"))
    countries.add(createCountry("tk", "+690", "Tokelau", "DDDD"))
    countries.add(createCountry("tl", "+670", "Timor-leste", "DDDD DDDD"))
    countries.add(createCountry("tm", "+993", "Turkmenistan", "DD DDDDDD"))
    countries.add(createCountry("tn", "+216", "Tunisia", "DD DDD DDD"))
    countries.add(createCountry("to", "+676", "Tonga", "DDD DDDD"))
    countries.add(createCountry("tr", "+90", "Turkey", "DDD DDD DD DD"))
    countries.add(createCountry("tt", "+1", "Trinidad &amp; Tobago", "DDD-DDD-DDDD"))
    countries.add(createCountry("tv", "+688", "Tuvalu",  "DDDDDD"))
    countries.add(createCountry("tw", "+886", "Taiwan",  "DDD DDD DDD"))
    countries.add(createCountry("tz", "+255", "Tanzania, United Republic Of",  "DDD DDD DDD"))
    countries.add(createCountry("ua", "+380", "Ukraine", "(DD) DDD-DD-DD"))
    countries.add(createCountry("ug", "+256", "Uganda",  "DDD DDDDDD"))
    countries.add(createCountry("us", "+1", "United States", "DDD-DDD-DDDD"))
    countries.add(createCountry("uy", "+598", "Uruguay", "DD DDD DDD"))
    countries.add(createCountry("uz", "+998", "Uzbekistan", "(DD) DDD-DD-DD"))
    countries.add(createCountry("va", "+379", "Holy See (vatican City State)", ""))
    countries.add(createCountry("vc", "+1-784", "Saint Vincent and the Grenadines", "DDD-DDDD"))
    countries.add(createCountry("ve", "+58", "Venezuela, Bolivarian Republic Of", "DDD-DDDDDDD"))
    countries.add(createCountry("vg", "+1-284", "British Virgin Islands", "DDD-DDDD"))
    countries.add(createCountry("vi", "+1-340", "US Virgin Islands", "DDD-DDDD"))
    countries.add(createCountry("vn", "+84", "Vietnam", "DD DDD DD DD"))
    countries.add(createCountry("vu", "+678", "Vanuatu", "DDD DDDD"))
    countries.add(createCountry("wf", "+681", "Wallis And Futuna", "DD DD DD"))
    countries.add(createCountry("ws", "4685", "Samoa", "DD DDDDD"))
    countries.add(createCountry("xk", "+383", "Kosovo", "DD DDD DDD"))
    countries.add(createCountry("ye", "+967", "Yemen", "DDD DDD DDD"))
    countries.add(createCountry("yt", "+262", "Mayotte", "DDD DD DD DD"))
    countries.add(createCountry("za", "+27", "South Africa", "DD DDD DDDD"))
    countries.add(createCountry("zm", "+260", "Zambia", "DD DDDDDDD"))
    countries.add(createCountry("zw", "+263", "Zimbabwe", "DD DDD DDDD"))
    return countries.filterNotNull()
}