package com.pschsch.kformatter.core.countries.internal

import com.pschsch.kformatter.core.countries.Countries
import com.pschsch.kformatter.core.countries.Country
import com.pschsch.kformatter.core.optin.IncubatingKFormatterAPI


@OptIn(IncubatingKFormatterAPI::class)
internal class CountriesImpl(
    private val countriesList: List<Country> = createCountriesList()
) : Countries, Collection<Country> by countriesList

@OptIn(IncubatingKFormatterAPI::class)
private fun createCountriesList(): List<Country> {
    var id = 0
    fun createCountry(
        code: String,
        phoneCode: String,
        englishName: String,
        separator: Char = ' ',
        mask: String = "(DD) DDD-DD-DD"
    ): Country {
        id += 1
        return Country(id, code, phoneCode, separator, mask, englishName)
    }

    val countries: MutableList<Country> = ArrayList()
    countries.add(createCountry("ad", "+376", "Andorra", mask = "DDD DDD"))
    countries.add(createCountry("ae", "+971", "United Arab Emirates (UAE)", mask = "DD DDD DDDD"))
    countries.add(createCountry("af", "+93", "Afghanistan", mask = "DD DDD DDDD"))
    countries.add(createCountry("ag", "+1", "Antigua and Barbuda", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("ai", "+1", "Anguilla", mask = "(DDD) DDD-DDDD"))
    countries.add(createCountry("al", "+355", "Albania", mask = "DD DDD DDDD"))
    countries.add(createCountry("am", "+374", "Armenia", mask = "DD DDDDDD"))
    countries.add(createCountry("ao", "+244", "Angola", mask = "DDD DDD DDD"))
    countries.add(createCountry("aq", "+672", "Antarctica", mask = "DDD DDD"))
    countries.add(createCountry("ar", "+54", "Argentina", mask = "D DD DDDD-DDDD"))
    countries.add(createCountry("as", "+1", "American Samoa", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("at", "+43", "Austria", mask = "DDD DDDDDD"))
    countries.add(createCountry("au", "+61", "Australia", mask = "DDD DDD DDD"))
    countries.add(createCountry("aw", "+297", "Aruba", mask = "DDD DDDD"))
    countries.add(createCountry("ax", "+358", "Åland Islands", mask = "DD DDDDDDD"))
    countries.add(createCountry("az", "+994", "Azerbaijan", mask = "(DD) DDD-DD-DD"))
    countries.add(createCountry("ba", "+387", "Bosnia And Herzegovina", mask = "DD DDD DDD"))
    countries.add(createCountry("bb", "+1", "Barbados", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("bd", "+880", "Bangladesh", mask = "DDDD-DDDDDD"))
    countries.add(createCountry("be", "+32", "Belgium", mask = "DDD DD DD DD"))
    countries.add(createCountry("bf", "+226", "Burkina Faso", mask = "DD DD DD DD"))
    countries.add(createCountry("bg", "+359", "Bulgaria", mask = "DD DDD DDD"))
    countries.add(createCountry("bh", "+973", "Bahrain", mask = "DDDD DDDD"))
    countries.add(createCountry("bi", "+257", "Burundi", mask = "DD DD DD DD"))
    countries.add(createCountry("bj", "+229", "Benin", mask = "DD DD DD DD"))
    countries.add(createCountry("bl", "+590", "Saint Barthélemy", mask = "DDD DD DD DD"))
    countries.add(createCountry("bm", "+1", "Bermuda", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("bn", "+673", "Brunei Darussalam", mask = "DDD DDDD"))
    countries.add(createCountry("bo", "+591", "Bolivia, Plurinational State Of", mask = "DDDD DDDD"))
    countries.add(createCountry("br", "+55", "Brazil", mask = "DD DDDDD-DDDD"))
    countries.add(createCountry("bs", "+1", "Bahamas", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("bt", "+975", "Bhutan", mask = "DD DD DD DD"))
    countries.add(createCountry("bw", "+267", "Botswana", mask = "DD DDD DDD"))
    countries.add(createCountry("by", "+375", "Belarus", mask = "(DD) DDD-DD-DD"))
    countries.add(createCountry("bz", "+501", "Belize", mask = "DDD-DDDD"))
    countries.add(createCountry("ca", "+1", "Canada", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("cc", "+61", "Cocos (keeling) Islands", mask = "DDD DDD DDD"))
    countries.add(createCountry("cd", "+243", "Congo, The Democratic Republic Of The", mask = "DDD DDD DDD"))
    countries.add(createCountry("cf", "+236", "Central African Republic", mask = "DD DD DD DD"))
    countries.add(createCountry("cg", "+242", "Congo", mask = "DDDD DDDD"))
    countries.add(createCountry("ch", "+41", "Switzerland", mask = "DD DDD DD DD"))
    countries.add(createCountry("ci", "+225", "Côte D'ivoire", mask = "DD DD DD DD"))
    countries.add(createCountry("ck", "+682", "Cook Islands", mask = "DD DDD"))
    countries.add(createCountry("cl", "+56", "Chile", mask = "D DDDD DDDD"))
    countries.add(createCountry("cm", "+237", "Cameroon"))
    countries.add(createCountry("cn", "+86", "China"))
    countries.add(createCountry("co", "+57", "Colombia"))
    countries.add(createCountry("cr", "+506", "Costa Rica"))
    countries.add(createCountry("cu", "+53", "Cuba"))
    countries.add(createCountry("cv", "+238", "Cape Verde"))
    countries.add(createCountry("cw", "+599", "Curaçao"))
    countries.add(createCountry("cx", "+61", "Christmas Island"))
    countries.add(createCountry("cy", "+357", "Cyprus"))
    countries.add(createCountry("cz", "+420", "Czech Republic"))
    countries.add(createCountry("de", "+49", "Germany"))
    countries.add(createCountry("dj", "+253", "Djibouti"))
    countries.add(createCountry("dk", "+45", "Denmark"))
    countries.add(createCountry("dm", "+1", "Dominica", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("do", "+1", "Dominican Republic", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("dz", "+213", "Algeria"))
    countries.add(createCountry("ec", "+593", "Ecuador"))
    countries.add(createCountry("ee", "+372", "Estonia"))
    countries.add(createCountry("eg", "+20", "Egypt"))
    countries.add(createCountry("er", "+291", "Eritrea"))
    countries.add(createCountry("es", "+34", "Spain"))
    countries.add(createCountry("et", "+251", "Ethiopia"))
    countries.add(createCountry("fi", "+358", "Finland"))
    countries.add(createCountry("fj", "+679", "Fiji"))
    countries.add(createCountry("fk", "+500", "Falkland Islands (malvinas)"))
    countries.add(createCountry("fm", "+691", "Micronesia, Federated States Of"))
    countries.add(createCountry("fo", "+298", "Faroe Islands"))
    countries.add(createCountry("fr", "+33", "France"))
    countries.add(createCountry("ga", "+241", "Gabon"))
    countries.add(createCountry("gb", "+44", "United Kingdom"))
    countries.add(createCountry("gd", "+1", "Grenada", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("ge", "+995", "Georgia", mask = "DDD-DDD-DDD"))
    countries.add(createCountry("gf", "+594", "French Guyana"))
    countries.add(createCountry("gh", "+233", "Ghana"))
    countries.add(createCountry("gi", "+350", "Gibraltar"))
    countries.add(createCountry("gl", "+299", "Greenland"))
    countries.add(createCountry("gm", "+220", "Gambia"))
    countries.add(createCountry("gn", "+224", "Guinea"))
    countries.add(createCountry("gp", "+450", "Guadeloupe"))
    countries.add(createCountry("gq", "+240", "Equatorial Guinea"))
    countries.add(createCountry("gr", "+30", "Greece"))
    countries.add(createCountry("gt", "+502", "Guatemala"))
    countries.add(createCountry("gu", "+1", "Guam", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("gw", "+245", "Guinea-bissau"))
    countries.add(createCountry("gy", "+592", "Guyana"))
    countries.add(createCountry("hk", "+852", "Hong Kong"))
    countries.add(createCountry("hn", "+504", "Honduras"))
    countries.add(createCountry("hr", "+385", "Croatia"))
    countries.add(createCountry("ht", "+509", "Haiti"))
    countries.add(createCountry("hu", "+36", "Hungary"))
    countries.add(createCountry("id", "+62", "Indonesia"))
    countries.add(createCountry("ie", "+353", "Ireland"))
    countries.add(createCountry("il", "+972", "Israel"))
    countries.add(createCountry("im", "+44", "Isle Of Man"))
    countries.add(createCountry("is", "+354", "Iceland"))
    countries.add(createCountry("in", "+91", "India"))
    countries.add(createCountry("io", "+246", "British Indian Ocean Territory"))
    countries.add(createCountry("iq", "+964", "Iraq"))
    countries.add(createCountry("ir", "+98", "Iran, Islamic Republic Of"))
    countries.add(createCountry("it", "+39", "Italy"))
    countries.add(createCountry("je", "+44", "Jersey "))
    countries.add(createCountry("jm", "+1", "Jamaica", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("jo", "+962", "Jordan"))
    countries.add(createCountry("jp", "+81", "Japan"))
    countries.add(createCountry("ke", "+254", "Kenya"))
    countries.add(createCountry("kg", "+996", "Kyrgyzstan", mask = "(DDD) DDD-DDD"))
    countries.add(createCountry("kh", "+855", "Cambodia"))
    countries.add(createCountry("ki", "+686", "Kiribati"))
    countries.add(createCountry("km", "+269", "Comoros"))
    countries.add(createCountry("kn", "+1", "Saint Kitts and Nevis", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("kp", "+850", "North Korea"))
    countries.add(createCountry("kr", "+82", "South Korea"))
    countries.add(createCountry("kw", "+965", "Kuwait"))
    countries.add(createCountry("ky", "+1", "Cayman Islands", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("kz", "+7", "Kazakhstan", mask = "(DDD) DDD-DD-DD"))
    countries.add(createCountry("la", "+856", "Lao People's Democratic Republic"))
    countries.add(createCountry("lb", "+961", "Lebanon"))
    countries.add(createCountry("lc", "+1", "Saint Lucia", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("li", "+423", "Liechtenstein"))
    countries.add(createCountry("lk", "+94", "Sri Lanka"))
    countries.add(createCountry("lr", "+231", "Liberia"))
    countries.add(createCountry("ls", "+266", "Lesotho"))
    countries.add(createCountry("lt", "+370", "Lithuania"))
    countries.add(createCountry("lu", "+352", "Luxembourg"))
    countries.add(createCountry("lv", "+371", "Latvia"))
    countries.add(createCountry("ly", "+218", "Libya"))
    countries.add(createCountry("ma", "+212", "Morocco"))
    countries.add(createCountry("mc", "+377", "Monaco"))
    countries.add(createCountry("md", "+373", "Moldova, Republic Of", mask = "DDD DDD-DD"))
    countries.add(createCountry("me", "+382", "Montenegro"))
    countries.add(createCountry("mf", "+590", "Saint Martin"))
    countries.add(createCountry("mg", "+261", "Madagascar"))
    countries.add(createCountry("mh", "+692", "Marshall Islands"))
    countries.add(createCountry("mk", "+389", "Macedonia (FYROM)"))
    countries.add(createCountry("ml", "+223", "Mali"))
    countries.add(createCountry("mm", "+95", "Myanmar"))
    countries.add(createCountry("mn", "+976", "Mongolia"))
    countries.add(createCountry("mo", "+853", "Macau"))
    countries.add(createCountry("mp", "+1", "Northern Mariana Islands", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("mq", "+596", "Martinique"))
    countries.add(createCountry("mr", "+222", "Mauritania"))
    countries.add(createCountry("ms", "+1", "Montserrat", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("mt", "+356", "Malta"))
    countries.add(createCountry("mu", "+230", "Mauritius"))
    countries.add(createCountry("mv", "+960", "Maldives"))
    countries.add(createCountry("mw", "+265", "Malawi"))
    countries.add(createCountry("mx", "+52", "Mexico"))
    countries.add(createCountry("my", "+60", "Malaysia"))
    countries.add(createCountry("mz", "+258", "Mozambique"))
    countries.add(createCountry("na", "+264", "Namibia"))
    countries.add(createCountry("nc", "+687", "New Caledonia"))
    countries.add(createCountry("ne", "+227", "Niger"))
    countries.add(createCountry("nf", "+672", "Norfolk Islands"))
    countries.add(createCountry("ng", "+234", "Nigeria"))
    countries.add(createCountry("ni", "+505", "Nicaragua"))
    countries.add(createCountry("nl", "+31", "Netherlands"))
    countries.add(createCountry("no", "+47", "Norway"))
    countries.add(createCountry("np", "+977", "Nepal"))
    countries.add(createCountry("nr", "+674", "Nauru"))
    countries.add(createCountry("nu", "+683", "Niue"))
    countries.add(createCountry("nz", "+64", "New Zealand"))
    countries.add(createCountry("om", "+968", "Oman"))
    countries.add(createCountry("pa", "+507", "Panama"))
    countries.add(createCountry("pe", "+51", "Peru"))
    countries.add(createCountry("pf", "+689", "French Polynesia"))
    countries.add(createCountry("pg", "+675", "Papua New Guinea"))
    countries.add(createCountry("ph", "+63", "Philippines"))
    countries.add(createCountry("pk", "+92", "Pakistan"))
    countries.add(createCountry("pl", "+48", "Poland"))
    countries.add(createCountry("pm", "+508", "Saint Pierre And Miquelon"))
    countries.add(createCountry("pn", "+870", "Pitcairn Islands"))
    countries.add(createCountry("pr", "+1", "Puerto Rico", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("ps", "+970", "Palestine"))
    countries.add(createCountry("pt", "+351", "Portugal"))
    countries.add(createCountry("pw", "+680", "Palau"))
    countries.add(createCountry("py", "+595", "Paraguay"))
    countries.add(createCountry("qa", "+974", "Qatar"))
    countries.add(createCountry("re", "+262", "Réunion"))
    countries.add(createCountry("ro", "+40", "Romania"))
    countries.add(createCountry("rs", "+381", "Serbia"))
    countries.add(createCountry("ru", "+7", "Russian Federation", mask = "(DDD) DDD-DD-DD"))
    countries.add(createCountry("rw", "+250", "Rwanda"))
    countries.add(createCountry("sa", "+966", "Saudi Arabia"))
    countries.add(createCountry("sb", "+677", "Solomon Islands"))
    countries.add(createCountry("sc", "+248", "Seychelles"))
    countries.add(createCountry("sd", "+249", "Sudan"))
    countries.add(createCountry("se", "+46", "Sweden"))
    countries.add(createCountry("sg", "+65", "Singapore"))
    countries.add(createCountry("sh", "+290", "Saint Helena, Ascension And Tristan Da Cunha"))
    countries.add(createCountry("si", "+386", "Slovenia"))
    countries.add(createCountry("sk", "+421", "Slovakia"))
    countries.add(createCountry("sl", "+232", "Sierra Leone"))
    countries.add(createCountry("sm", "+378", "San Marino"))
    countries.add(createCountry("sn", "+221", "Senegal"))
    countries.add(createCountry("so", "+252", "Somalia"))
    countries.add(createCountry("sr", "+597", "Suriname"))
    countries.add(createCountry("ss", "+211", "South Sudan"))
    countries.add(createCountry("st", "+239", "Sao Tome And Principe"))
    countries.add(createCountry("sv", "+503", "El Salvador"))
    countries.add(createCountry("sx", "+1", "Sint Maarten", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("sy", "+963", "Syrian Arab Republic"))
    countries.add(createCountry("sz", "+268", "Swaziland"))
    countries.add(createCountry("tc", "+1", "Turks and Caicos Islands", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("td", "+235", "Chad"))
    countries.add(createCountry("tg", "+228", "Togo"))
    countries.add(createCountry("th", "+66", "Thailand"))
    countries.add(createCountry("tj", "+992", "Tajikistan"))
    countries.add(createCountry("tk", "+690", "Tokelau"))
    countries.add(createCountry("tl", "+670", "Timor-leste"))
    countries.add(createCountry("tm", "+993", "Turkmenistan"))
    countries.add(createCountry("tn", "+216", "Tunisia"))
    countries.add(createCountry("to", "+676", "Tonga"))
    countries.add(createCountry("tr", "+90", "Turkey"))
    countries.add(createCountry("tt", "+1", "Trinidad &amp; Tobago", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("tv", "+688", "Tuvalu"))
    countries.add(createCountry("tw", "+886", "Taiwan"))
    countries.add(createCountry("tz", "+255", "Tanzania, United Republic Of"))
    countries.add(createCountry("ua", "+380", "Ukraine", mask = "(DD) DDD-DD-DD"))
    countries.add(createCountry("ug", "+256", "Uganda"))
    countries.add(createCountry("us", "+1", "United States", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("uy", "+598", "Uruguay"))
    countries.add(createCountry("uz", "+998", "Uzbekistan", mask = "(DD) DDD-DD-DD"))
    countries.add(createCountry("va", "+379", "Holy See (vatican City State)"))
    countries.add(createCountry("vc", "+1", "Saint Vincent &amp; The Grenadines", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("ve", "+58", "Venezuela, Bolivarian Republic Of"))
    countries.add(createCountry("vg", "+1", "British Virgin Islands", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("vi", "+1", "US Virgin Islands", mask = "DDD-DDD-DDDD"))
    countries.add(createCountry("vn", "+84", "Vietnam"))
    countries.add(createCountry("vu", "+678", "Vanuatu"))
    countries.add(createCountry("wf", "+681", "Wallis And Futuna"))
    countries.add(createCountry("ws", "4685", "Samoa"))
    countries.add(createCountry("xk", "+383", "Kosovo"))
    countries.add(createCountry("ye", "+967", "Yemen"))
    countries.add(createCountry("yt", "+262", "Mayotte"))
    countries.add(createCountry("za", "+27", "South Africa"))
    countries.add(createCountry("zm", "+260", "Zambia"))
    countries.add(createCountry("zw", "+263", "Zimbabwe"))
    return countries
}